---
title: "Diagnosis of common skin cancers"
date: "`r format(Sys.time(), '%B %d, %Y')`"
#bibliography: [Refs/_ClinVal.bib, Refs/GRAIL_Liu_2020/_GRAIL_Liu_2020.bib,
#               Refs/Liu_2025/_Liu_2025.bib]
csl: ../_csl/cell-numeric.csl
link-citations: true
always_allow_html: yes
output:
  #html_document:
  # for use of .tabset
  rmarkdown::html_document:
    code_folding: hide
    code_download: true
    toc: false
    toc_depth: 2
    # does this have an effect
    fig_caption: yes
    # this has no effect
    number_sections: yes
    # css: ['../_css/pandoc3.css', '../_css/myMargins.css']
---

<!-- 

<p style="background-color: yellow; padding: 5px;">
  <span style="font-weight: bold;">⚠️ Work in Progress:</span> This content is incomplete.
</p>

-->

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = NA,
                      warning = FALSE,
                      error = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.width = 8,
                      fig.height = 4)
```


```{r index-GlobalOptions, results="hide", include=FALSE, cache=FALSE}

knitr::opts_knit$set(stop_on_error = 2L) #really make it stop
options(knitr.table.format = 'html')

options(stringsAsFactors=F)

 #knitr::dep_auto()

```
<!-- ######################################################################## -->


```{r index-Prelims,  include=FALSE, echo=FALSE, results='hide', message=FALSE} 


FN <- "index"
if(sum(grepl(FN, list.files()))==0) stop("Check FN")

PREFIX <- "index" #- replace by FLOWCELL???

 suppressMessages(require(rmarkdown))
 suppressMessages(require(knitr))

 suppressPackageStartupMessages(require(methods))
 suppressPackageStartupMessages(require(bookdown))

 suppressPackageStartupMessages(require(magrittr))

 # Shotcuts for knitting and rendering while in R session (Invoke interactive R from R/Scripts folder)
 kk <- function(n='') knitr::knit2html(paste("t", n, sep=''), envir=globalenv(),
       output=paste(FN,".html", sep=''))

 rr <- function(n='') rmarkdown::render(paste("t", n, sep=''), envir=globalenv(),
       output_file=paste(FN,".html", sep='')) ##, output_dir='Scripts')

 bb <- function(n='') browseURL(paste(FN,".html", sep=''))

 # The usual shortcuts
 zz <- function(n='') source(paste("t", n, sep=''))

```
<!-- ######################################################################## -->

<br/>

#  Introduction - IOM Translation Omics

* [Evolution of Translational Omics: Lessons Learned and the Path Forward](https://pubmed.ncbi.nlm.nih.gov/24872966/)

*  [ppt](Refs/OmicsTests.pptx)


<br/>

# Context of Current work

<br/>

## Varieties of GAI in Tx Omics  {-}

## Varieties of Biomarkers to Detect Skin Cancer {-}

## Varieties of Classifiers based on micRNA {-}

<br/>




<!--

<br/>

 References 

<div id="refs"></div>

-->

<br/>


```{r, echo=FALSE}
  knitr::knit_exit()
```

###########################################################
 ARCHIVED CODE BELOW
###########################################################


    
<!-- To run
# nohup Rscript -e "knitr::knit2html('index.Rmd')" > index.log  &
    
# Or 
# nohup Rscript -e "rmarkdown::render('index.Rmd')" > index.log  &
    
-->
